server:
  port: ${MOVIE_MATE_API_GATEWAY_PORT:7080}

spring:
  application:
    name: api-gateway

gateway:
  routes:
    user-service-uri: ${MOVIE_MATE_USER_SERVICE_URI}
    watchlist-service-uri: ${MOVIE_MATE_WATCHLIST_SERVICE_URI}
    movie-service-uri: ${MOVIE_MATE_MOVIE_SERVICE_URI}
    activity-service-uri: ${MOVIE_MATE_ACTIVITY_SERVICE_URI}
    recommendations-service-uri: ${MOVIE_MATE_RECOMMENDATION_SERVICE_URI}

    users-base-path:
      original: ${MOVIE_MATE_GATEWAY_USERS_ORIGINAL_BASE_PATH}
      target: ${MOVIE_MATE_GATEWAY_USERS_TARGET_BASE_PATH}

    watchlists-base-path:
      original: ${MOVIE_MATE_GATEWAY_WATCHLISTS_ORIGINAL_BASE_PATH}
      target: ${MOVIE_MATE_GATEWAY_WATCHLISTS_TARGET_BASE_PATH}

    movies-base-path:
      original: ${MOVIE_MATE_GATEWAY_MOVIES_ORIGINAL_BASE_PATH}
      target: ${MOVIE_MATE_GATEWAY_MOVIES_TARGET_BASE_PATH}

    activity-base-path:
      original: ${MOVIE_MATE_GATEWAY_ACTIVITY_ORIGINAL_BASE_PATH}
      target: ${MOVIE_MATE_GATEWAY_ACTIVITY_TARGET_BASE_PATH}

    recommendations-base-path:
      original: ${MOVIE_MATE_GATEWAY_RECOMMENDATION_ORIGINAL_BASE_PATH}
      target: ${MOVIE_MATE_GATEWAY_RECOMMENDATION_TARGET_BASE_PATH}

logging:
  level:
    org:
      springframework: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: ${MOVIE_MATE_DISCOVERY_SERVER_URL}
    registerWithEureka: true
    fetchRegistry: true
