server:
  port: ${MOVIE_MATE_API_GATEWAY_PORT:7080}

spring:
  application:
    name: api-gateway


logging:
  level:
    org:
      springframework: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: ${MOVIE_MATE_DISCOVERY_SERVER_URL}
    registerWithEureka: true
    fetchRegistry: true
