server:
  port: ${MOVIE_MATE_USER_SERVICE_PORT:7030}
  servlet:
    context-path: ${MOVIE_MATE_USER_SERVICE_CONTEXT_PATH:/api/v1}

spring:
  datasource:
    url: ${MOVIE_MATE_USER_SERVICE_DATASOURCE_URL}
    username: ${MOVIE_MATE_USER_SERVICE_DATASOURCE_USERNAME}
    password: ${MOVIE_MATE_USER_SERVICE_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
#        show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
    host: ${MOVIE_MATE_USER_SERVICE_REDIS_HOST}
    port: ${MOVIE_MATE_USER_SERVICE_REDIS_PORT:6379}
    database-idx: ${MOVIE_MATE_USER_SERVICE_DATABASE_INDEX:0}
    password: ${MOVIE_MATE_USER_SERVICE_REDIS_PASSWORD}
    ttl: ${MOVIE_MATE_USER_SERVICE_REDIS_TTL}
  application:
    name: user-service

security:
  jwt:
    secret-key: ${MOVIE_MATE_JWT_SECRET_KEY}
    access-expiration: ${MOVIE_MATE_JWT_ACCESS_EXPIRATION_TIME}
    refresh-expiration: ${MOVIE_MATE_JWT_REFRESH_EXPIRATION_TIME}
  root-user:
    username: ${MOVIE_MATE_USER_SERVICE_ROOT_USERNAME}
    email: ${MOVIE_MATE_USER_SERVICE_ROOT_EMAIL}
    password: ${MOVIE_MATE_USER_SERVICE_ROOT_PASSWORD}

logging:
  level:
    org:
      springframework: INFO

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/swagger-ui.html