server:
  port: ${MOVIE_MATE_USER_SERVICE_PORT:7030}

spring:
  application:
    name: user-service

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration: ${JWT_ACCESS_EXPIRATION_TIME}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION_TIME}

logging:
  level:
    org:
      springframework: INFO