server:
  port: ${MOVIE_MATE_DISCOVERY_SERVER_PORT:7070}
  servlet:
    context-path: /movie-mate/lb-server
spring:
  application:
    name: discovery-server

logging:
  level:
    org:
      springframework: INFO

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${MOVIE_MATE_DISCOVERY_SERVER_URL}
  server:
    enable-self-preservation: true
    evictionIntervalTimerInMs: 60000
