server:
  port: ${MOVIE_MATE_DISCOVERY_SERVER_PORT:7070}

spring:
  application:
    name: discovery-server

logging:
  level:
    org:
      springframework: INFO

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: true
    evictionIntervalTimerInMs: 60000
