server:
  port: ${MOVIE_MATE_MOVIE_SERVICE_PORT:7060}
  servlet:
    context-path: ${MOVIE_MATE_MOVIE_SERVICE_CONTEXT_PATH:/api/v1/movie}

spring:
  application:
    name: movie-service

  data:
    mongodb:
#      username: ${MOVIE_MATE_MONGO_USERNAME}
#      password: ${MOVIE_MATE_MONGO_PASSWORD}
      database: ${MOVIE_MATE_MOVIE_SERVICE_MONGO_DB}
      host: ${MOVIE_MATE_MONGO_HOST}
      port: ${MOVIE_MATE_MONGO_PORT}

  cache:
    type: redis
    host: ${MOVIE_MATE_REDIS_HOST}
    port: ${MOVIE_MATE_REDIS_PORT:6379}
    database-idx: ${MOVIE_MATE_MOVIE_SERVICE_DATABASE_INDEX:1}
    password: ${MOVIE_MATE_REDIS_PASSWORD}
    ttl: ${MOVIE_MATE_MOVIE_SERVICE_REDIS_TTL:-1}

logging:
  level:
    org:
      springframework: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: ${MOVIE_MATE_DISCOVERY_SERVER_URL}
    registerWithEureka: true
    fetchRegistry: true