server:
  port: ${MOVIE_MATE_MOVIE_SERVICE_PORT:7060}
  servlet:
    context-path: ${MOVIE_MATE_MOVIE_SERVICE_CONTEXT_PATH:/api/v1/movie}

spring:
  application:
    name: movie-service

  data:
    mongodb:
      authentication-database: ${MOVIE_MATE_MOVIE_SERVICE_MONGO_AUTH_DB}
      username: ${MOVIE_MATE_MOVIE_SERVICE_MONGO_USERNAME}
      password: ${MOVIE_MATE_MOVIE_SERVICE_MONGO_PASSWORD}
      database: ${MOVIE_MATE_MOVIE_SERVICE_MONGO_DB}
      host: ${MOVIE_MATE_MOVIE_SERVICE_MONGO_HOST}
      port: ${MOVIE_MATE_MOVIE_SERVICE_MONGO_PORT}

  cache:
    type: redis
    host: ${MOVIE_MATE_MOVIE_SERVICE_REDIS_HOST}
    port: ${MOVIE_MATE_MOVIE_SERVICE_REDIS_PORT:6379}
    database-idx: ${MOVIE_MATE_MOVIE_SERVICE_DATABASE_INDEX:1}
    password: ${MOVIE_MATE_MOVIE_SERVICE_REDIS_PASSWORD}
    ttl: ${MOVIE_MATE_MOVIE_SERVICE_REDIS_TTL}

logging:
  level:
    org:
      springframework: INFO
