name: Deploy System

on:
  push:
    branches:
      - test # Change to your branch (e.g., 'test')

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.MANKI_SERVER_PORT }} ${{ secrets.MANKI_SERVER }} >> ~/.ssh/known_hosts

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -J ${{ secrets.MANKI_SERVER_USER }}@${{ secrets.MANKI_SERVER }}:${{ secrets.MANKI_SERVER_PORT }} -p ${{ secrets.MANKI_HOME_SERVER_PORT }} ${{ secrets.MANKI_HOME_SERVER_USER }}@${{ secrets.MANKI_HOME_SERVER }} << 'EOF'
            cd ~/Documents/movie-mate-system
            git pull origin
            git checkout test
            docker compose down
            docker compose up -d
          EOF
